spring.application.name=API-Firmas
app.storage.ruta-compartida= \\\\192.1.1.104\\Temporal\\Entregables\\firmas
spring.datasource.url=jdbc:sqlserver://192.1.1.104;databaseName=PacificaV2;encrypt=false;trustServerCertificate=true;
spring.datasource.username=web2
spring.datasource.password=Pacifica312
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
